---

name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Cache
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # Setup
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Set up Nodejs 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Set up ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install dependencies
        run: npm i
      - name: Install ruby dependencies
        run: gem install cfn-nag
      # Build
      - name: Run build
        run: npm run build
      # Run Tests
      - name: CloudFormation lint
        run: npm t
      - name: CloudFormation nag
        run: cfn_nag templates/template.yaml
